"""empty message

Revision ID: 649f57ea4b96
Revises: 5a79b7928671
Create Date: 2021-04-14 16:37:58.136145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649f57ea4b96'
down_revision = '5a79b7928671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_changes', sa.Column('first_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_changes', 'first_image')
    # ### end Alembic commands ###
