"""empty message

Revision ID: 69349a49d444
Revises: c8406d691264
Create Date: 2021-04-15 15:49:56.006909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69349a49d444'
down_revision = 'c8406d691264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('user_login_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'login')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('login', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_login_key', 'user', ['login'])
    op.drop_column('user', 'active')
    op.drop_table('roles_users')
    op.drop_table('roles')
    # ### end Alembic commands ###
