"""empty message

Revision ID: c8406d691264
Revises: 649f57ea4b96
Create Date: 2021-04-14 17:21:28.531413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8406d691264'
down_revision = '649f57ea4b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_changes', sa.Column('second_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_changes', 'second_image')
    # ### end Alembic commands ###
